In [57]:
import pandas as pd

In [58]:
df=pd.read_json('test.json')
df.head()

      id                                        ingredients
0  18009  [baking powder, eggs, all-purpose flour, raisi...
1  28583  [sugar, egg yolks, corn starch, cream of tarta...
2  41580  [sausage links, fennel bulb, fronds, olive oil...
3  29752  [meat cuts, file powder, smoked sausage, okra,...
4  35687  [ground black pepper, salt, sausage casings, l...

In [59]:
df.shape

(9944, 2)

# Clean the dataset

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9944 entries, 0 to 9943
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           9944 non-null   int64
 1   ingredients  9944 non-null   object
dtypes: int64(1), object(1)
memory usage: 155.5+ KB

In [61]:
# Check if the dataset has null values

In [62]:
df.isnull().sum()

id             0
ingredients    0
dtype: int64

In [63]:
df = df.iloc[:, 1:]

In [64]:
df.head()

                                         ingredients
0  [baking powder, eggs, all-purpose flour, raisi...
1  [sugar, egg yolks, corn starch, cream of tarta...
2  [sausage links, fennel bulb, fronds, olive oil...
3  [meat cuts, file powder, smoked sausage, okra,...
4  [ground black pepper, salt, sausage casings, l...

In [65]:
type(df["ingredients"].iloc[0])  # checking if the data is a list or String

list

In [66]:
df['ingredients'].head() #pandas stores lists as objects

0    [baking powder, eggs, all-purpose flour, raisi...
1    [sugar, egg yolks, corn starch, cream of tarta...
2    [sausage links, fennel bulb, fronds, olive oil...
3    [meat cuts, file powder, smoked sausage, okra,...
4    [ground black pepper, salt, sausage casings, l...
Name: ingredients, dtype: object

In [67]:
df['ingredients'] = df['ingredients'].apply(lambda x: [item.lower() for item in x])   #changes list into lower case

In [68]:
df['ingredients'].iloc[0][0].islower()

True

In [56]:
df['ingredients'].iloc[0] #check if all are in lower case

['baking powder',
 'all-purpose flour',
 'peach slices',
 'corn starch',
 'heavy cream',
 'lemon juice',
 'unsalted butter',
 'salt',
 'white sugar']